server:
  port: 8081
  servlet:
    context-path: /web
spring:
  http:
    converters:
      preferred-json-mapper: gson
  elasticsearch:
    jest:
      uris:
        - http://192.168.0.107:9207
      kerberos:
        username: kerberos
        enabled: false
