server:
  port: 8081
  servlet:
    context-path: /web
spring:
  elasticsearch:
    rest:
      uris:
        - 192.168.0.107:9207
      kerberos:
        username: kerberos
        enabled: false
      compatible: true